name: Rust

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Cache
              uses: Swatinem/rust-cache@v2

            - name: Formatting
              run: cargo fmt --check

            - name: Lint
              run: cargo clippy

            - name: Build
              run: cargo build --release && mv target/release/saild saild-x86_64-linux

            - name: Run unit tests
              run: cargo test

            #    - name: Run integration tests
            #      run: cargo test send_trigger -- --ignored
            #      env:
            #        TRIGGER_EMAIL: ${{ secrets.TRIGGER_EMAIL }}

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: builds
                  retention-days: 7
                  path: saild-x86_64-linux
